import {
    AlertCircle,
    AlertTriangle,
    ArrowRight,
    Check,
    CheckSquare,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Command,
    CreditCard,
    Crown,
    Edit,
    File,
    FileText,
    Folder,
    Github,
    HelpCircle,
    Home,
    Image,
    Laptop,
    LogOut,
    LucideIcon,
    Moon,
    MoreVertical,
    Pizza,
    Plus,
    Settings,
    SunMedium,
    Trash,
    Twitter,
    User,
    Users,
    X,
} from 'lucide-react';
import { Loader } from './loader';

export type TIcon = LucideIcon;

export const Icons = {
    logo: Command,
    close: X,
    spinner: (props: any) => <Loader {...props} />,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronDown: ChevronDown,
    chevronUp: ChevronUp,
    trash: Trash,
    post: FileText,
    page: File,
    media: Image,
    settings: Settings,
    billing: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    plus: Plus,
    warning: AlertCircle,
    alertTriangle: AlertTriangle,
    user: User,
    users: Users,
    arrowRight: ArrowRight,
    help: HelpCircle,
    pizza: Pizza,
    sun: SunMedium,
    moon: Moon,
    laptop: Laptop,
    gitHub: Github,
    twitter: Twitter,
    check: Check,
    checkSquare: CheckSquare,
    home: Home,
    folder: Folder,
    edit: Edit,
    logOut: LogOut,
    crown: Crown,
} as const;
